/**
 * Seed script — Real Indian Legal Provisions
 * Run: npx ts-node src/db/seedLegalProvisions.ts
 * Covers: BNS 2023 (replaced IPC), BNSS 2023 (replaced CrPC), BSA 2023 (replaced IEA),
 *         IT Act 2000, NDPS Act 1985, POCSO Act 2012, Dowry Prohibition Act,
 *         Arms Act, Motor Vehicles Act, Prevention of Corruption Act
 */

import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import LegalProvision from '../models/LegalProvision';

const PROVISIONS = [
  // ─── BNS 2023 (Bharatiya Nyaya Sanhita) ──────────────────────────────────
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '101',
    title: 'Culpable Homicide',
    description: 'Whoever causes death by doing an act intending to cause death or knowing that act is likely to cause death commits culpable homicide.',
    plain_language: 'Intentionally or knowingly causing the death of another person.',
    offense_category: 'Homicide',
    punishment: 'Imprisonment for life, or imprisonment up to 10 years, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Post-mortem report', 'Eyewitness statements', 'Weapon used', 'CCTV footage', 'Forensic report'],
    keywords: ['death', 'homicide', 'killing', 'murder', 'culpable', 'died', 'deceased'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '103',
    title: 'Murder',
    description: 'Culpable homicide is murder if the act is done with intention of causing death, or with the intention of causing such bodily injury as the offender knows to be likely to cause death, or is sufficient in the ordinary course of nature to cause death.',
    plain_language: 'The most serious form of intentional killing — deliberate murder.',
    offense_category: 'Homicide',
    punishment: 'Death or imprisonment for life, and fine. For group killing: death or life imprisonment',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Post-mortem report', 'Weapon', 'Eyewitness', 'CCTV', 'Call records', 'Forensic ballistics'],
    keywords: ['murder', 'killed', 'homicide', 'death', 'shot', 'stabbed', 'poisoned', 'lynching'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '105',
    title: 'Culpable Homicide by Negligence',
    description: 'Whoever causes death by a rash or negligent act not amounting to culpable homicide.',
    plain_language: 'Accidental death caused by careless or reckless behaviour.',
    offense_category: 'Negligence',
    punishment: 'Imprisonment up to 5 years and fine; if driver causes death and flees — up to 10 years',
    is_bailable: true,
    is_cognizable: true,
    typical_evidence: ['Post-mortem report', 'Accident report', 'Vehicle inspection', 'Witnesses', 'CCTV'],
    keywords: ['accident', 'negligence', 'rash driving', 'reckless', 'accidental death', 'hit and run'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '109',
    title: 'Abetment of Suicide',
    description: 'If any person commits suicide, whoever abets the commission of such suicide shall be punished.',
    plain_language: 'Instigating, encouraging, or aiding someone to commit suicide.',
    offense_category: 'Abetment',
    punishment: 'Imprisonment up to 10 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Suicide note', 'Call records', 'WhatsApp messages', 'Witness statements', 'Bank records'],
    keywords: ['suicide', 'abetment', 'instigate', 'harass', 'dowry death', 'mental cruelty'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '115',
    title: 'Voluntarily Causing Hurt',
    description: 'Whoever does any act with the intention of thereby causing hurt to any person, or with the knowledge that he is likely thereby to cause hurt to any person, and does thereby cause hurt to any person.',
    plain_language: 'Physically injuring or assaulting another person intentionally.',
    offense_category: 'Assault & Hurt',
    punishment: 'Imprisonment up to 1 year, or fine up to Rs. 10,000, or both',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Medical examination report', 'Injury certificate', 'Witness statements', 'CCTV footage'],
    keywords: ['assault', 'hurt', 'beaten', 'injured', 'attack', 'slapped', 'punched'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '117',
    title: 'Voluntarily Causing Grievous Hurt',
    description: 'Whoever voluntarily causes grievous hurt shall be punished. Grievous hurt includes permanent disfigurement, loss of limb, or endangering life.',
    plain_language: 'Causing serious bodily injury such as broken bones, loss of limb, or permanent damage.',
    offense_category: 'Assault & Hurt',
    punishment: 'Imprisonment up to 7 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical report', 'X-ray/MRI', 'Witness statements', 'Weapon', 'CCTV'],
    keywords: ['grievous hurt', 'grievous injury', 'broken bone', 'acid attack', 'serious assault', 'fracture'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '121',
    title: 'Acid Attack',
    description: 'Whoever throws or administers acid on any person with the intention of causing permanent or partial damage or deformity or burns.',
    plain_language: 'Throwing acid on someone causing burns, disfigurement, or disability.',
    offense_category: 'Acid Attack',
    punishment: 'Imprisonment not less than 10 years, may extend to life imprisonment, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical report', 'Forensic report on acid', 'CCTV', 'Witness statements', 'Purchase records of acid'],
    keywords: ['acid attack', 'acid thrown', 'burns', 'chemical attack', 'disfigurement'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '126',
    title: 'Wrongful Restraint',
    description: 'Whoever voluntarily obstructs any person so as to prevent that person from proceeding in any direction in which that person has a right to proceed.',
    plain_language: 'Stopping or blocking someone from moving freely.',
    offense_category: 'Wrongful Restraint',
    punishment: 'Simple imprisonment up to 1 month, or fine up to Rs. 5,000, or both',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Witness statements', 'CCTV footage', 'Complainant statement'],
    keywords: ['wrongful restraint', 'blocked', 'stopped', 'obstructed', 'prevented movement'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '127',
    title: 'Wrongful Confinement',
    description: 'Whoever wrongfully restrains any person in such a manner as to prevent that person from proceedings beyond certain circumscribing limits.',
    plain_language: 'Illegally imprisoning or confining a person against their will.',
    offense_category: 'Wrongful Confinement',
    punishment: 'Imprisonment up to 1 year, or fine up to Rs. 5,000, or both; aggravated cases up to 3 years',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Victim statement', 'Witness statements', 'Medical examination', 'CCTV'],
    keywords: ['confined', 'locked up', 'imprisoned', 'wrongful confinement', 'held captive'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '140',
    title: 'Kidnapping from India',
    description: 'Whoever conveys any person beyond the limits of India without the consent of that person, or of some person legally authorised to consent on behalf of that person.',
    plain_language: 'Taking a person out of India without their consent.',
    offense_category: 'Kidnapping',
    punishment: 'Imprisonment up to 7 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Passport records', 'Immigration records', 'Witness statements', 'Call records'],
    keywords: ['kidnapping', 'abduction', 'taken abroad', 'missing', 'transported'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '141',
    title: 'Kidnapping from Lawful Guardianship',
    description: 'Whoever takes or entices any minor under sixteen years of age if a male, or under eighteen years of age if a female, or any person of unsound mind, out of the keeping of the lawful guardian.',
    plain_language: 'Taking a minor away from their legal guardian without consent.',
    offense_category: 'Kidnapping',
    punishment: 'Imprisonment up to 7 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Birth certificate', 'Guardian statement', 'CCTV', 'Call records', 'Witness statements'],
    keywords: ['child kidnapping', 'minor abducted', 'taken from guardian', 'missing child', 'enticement'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '143',
    title: 'Kidnapping for Ransom',
    description: 'Whoever kidnaps or abducts any person with intent to hold for ransom or to commit grievous hurt, or to cause death.',
    plain_language: 'Kidnapping a person and demanding money or other consideration for their release.',
    offense_category: 'Kidnapping',
    punishment: 'Death or imprisonment for life, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Ransom call recordings', 'Bank transfer records', 'Witness statements', 'Call records', 'CCTV'],
    keywords: ['kidnapping for ransom', 'ransom demand', 'hostage', 'abduction for money'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '63',
    title: 'Rape',
    description: 'A man is said to commit rape if he penetrates without consent or against the will of the woman, or with a woman under 18 years of age.',
    plain_language: 'Sexual assault involving penetration without consent or with a minor.',
    offense_category: 'Sexual Offence',
    punishment: 'Rigorous imprisonment not less than 10 years, may extend to life imprisonment, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical examination (rape kit)', 'Victim statement', 'Forensic DNA report', 'CCTV', 'Call records'],
    keywords: ['rape', 'sexual assault', 'sexual violence', 'penetration', 'non-consensual', 'molest'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '64',
    title: 'Punishment for Rape',
    description: 'Whoever commits rape shall be punished with rigorous imprisonment of either description for a term which shall not be less than ten years but which may extend to imprisonment for life.',
    plain_language: 'Punishment provisions for rape — minimum 10 years rigorous imprisonment.',
    offense_category: 'Sexual Offence',
    punishment: 'Rigorous imprisonment not less than 10 years to life, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical report', 'DNA evidence', 'Victim statement', 'Witness statements'],
    keywords: ['rape punishment', 'sexual assault penalty', 'gang rape', 'custodial rape'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '74',
    title: 'Assault or Use of Criminal Force with Intent to Outrage Modesty',
    description: 'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty.',
    plain_language: 'Sexually assaulting or groping a woman without penetration.',
    offense_category: 'Sexual Offence',
    punishment: 'Imprisonment up to 5 years, and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Victim statement', 'Medical examination', 'CCTV', 'Witness statements'],
    keywords: ['outrage modesty', 'molestation', 'eve teasing', 'groping', 'touching without consent', 'sexual harassment'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '79',
    title: 'Voyeurism',
    description: 'Whoever watches, or captures the image of, a woman engaging in a private act in circumstances where she would usually have the expectation of not being observed.',
    plain_language: 'Secretly watching or filming a woman in private without her consent.',
    offense_category: 'Sexual Offence',
    punishment: 'Imprisonment not less than 1 year, up to 3 years for first offence; up to 7 years for subsequent offence',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Camera/device seized', 'Digital forensic report', 'Victim statement', 'Recording evidence'],
    keywords: ['voyeurism', 'hidden camera', 'spy cam', 'secretly filmed', 'upskirt', 'private video'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '303',
    title: 'Theft',
    description: 'Whoever intending to take dishonestly any moveable property out of the possession of any person without that person\'s consent moves that property.',
    plain_language: 'Taking someone\'s property without their consent with the intention to permanently deprive them of it.',
    offense_category: 'Property Offence',
    punishment: 'Imprisonment up to 3 years, or fine, or both',
    is_bailable: true,
    is_cognizable: true,
    typical_evidence: ['Complainant statement', 'CCTV footage', 'Recovery of stolen property', 'Witness statements'],
    keywords: ['theft', 'stolen', 'stealing', 'pickpocket', 'shoplifting', 'property stolen', 'missing property'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '304',
    title: 'Theft in Dwelling House',
    description: 'Whoever commits theft in a building, tent or vessel which is used as a human dwelling or for custody of property.',
    plain_language: 'Stealing from a residence, house, or building used as a dwelling.',
    offense_category: 'Property Offence',
    punishment: 'Imprisonment up to 7 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Scene of crime inspection', 'Fingerprints', 'CCTV', 'Neighbour statements', 'Stolen article recovery'],
    keywords: ['house theft', 'burglary', 'home robbery', 'dwelling theft', 'household theft'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '309',
    title: 'Robbery',
    description: 'In all robbery there is either theft or extortion. Theft is robbery if in order to commit the theft the offender voluntarily causes or attempts to cause to any person death, hurt or wrongful restraint.',
    plain_language: 'Theft using force, threat, or violence against the victim.',
    offense_category: 'Property Offence',
    punishment: 'Rigorous imprisonment up to 10 years and fine; on highway — up to 14 years',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Victim statement', 'Medical report', 'CCTV footage', 'Recovery of property', 'Witness statements'],
    keywords: ['robbery', 'snatching', 'chain snatching', 'mugging', 'loot', 'looted', 'forceful theft'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '310',
    title: 'Dacoity',
    description: 'When five or more persons conjointly commit or attempt to commit a robbery, or where the whole number of persons conjointly committing or attempting to commit a robbery amounts to five or more, every person so committing or attempting is said to commit dacoity.',
    plain_language: 'Robbery committed by a gang of five or more persons together.',
    offense_category: 'Property Offence',
    punishment: 'Imprisonment for life or rigorous imprisonment up to 10 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Victim statements', 'CCTV footage', 'Recovery of weapons', 'Recovery of property', 'Witness statements'],
    keywords: ['dacoity', 'gang robbery', 'armed robbery', 'looting by gang', 'five or more persons'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '316',
    title: 'Criminal Breach of Trust',
    description: 'Whoever, being in any manner entrusted with property, or with any dominion over property, dishonestly misappropriates or converts to his own use that property.',
    plain_language: 'Misusing property or money that was entrusted to you for safekeeping or a specific purpose.',
    offense_category: 'Property Offence',
    punishment: 'Imprisonment up to 3 years, or fine, or both; aggravated cases up to 7 years',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Account statements', 'Receipts/vouchers', 'Agreement documents', 'Bank records', 'Witness statements'],
    keywords: ['breach of trust', 'misappropriation', 'embezzlement', 'misuse of funds', 'trust violated'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '318',
    title: 'Cheating',
    description: 'Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property.',
    plain_language: 'Deceiving someone to dishonestly obtain money, property, or advantage from them.',
    offense_category: 'Fraud & Cheating',
    punishment: 'Imprisonment up to 3 years, or fine, or both; if causes delivery of property — up to 7 years',
    is_bailable: false,
    is_cognizable: false,
    typical_evidence: ['Bank statements', 'Communication records', 'Contracts', 'Witness statements', 'Digital evidence'],
    keywords: ['cheating', 'fraud', 'deceived', 'scam', 'bogus', 'fake promise', 'job fraud', 'online fraud'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '319',
    title: 'Cheating by Personation',
    description: 'A person is said to cheat by personation if he cheats by pretending to be some other person, or by knowingly substituting one person for another.',
    plain_language: 'Committing fraud by pretending to be someone else — fake identity or impersonation.',
    offense_category: 'Fraud & Cheating',
    punishment: 'Imprisonment up to 5 years, or fine, or both',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Fake ID documents', 'Digital records', 'Witness statements', 'Bank records'],
    keywords: ['personation', 'impersonation', 'fake identity', 'identity theft', 'false identity', 'posing as'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '329',
    title: 'Mischief',
    description: 'Whoever with intent to cause, or knowing that he is likely to cause, wrongful loss or damage to the public or to any person, causes the destruction of any property.',
    plain_language: 'Intentionally damaging or destroying someone\'s property.',
    offense_category: 'Property Offence',
    punishment: 'Imprisonment up to 3 months, or fine, or both; causing substantial loss — up to 5 years',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Site inspection', 'Photographs', 'Damage assessment report', 'CCTV', 'Witness statements'],
    keywords: ['mischief', 'property damage', 'vandalism', 'destroyed property', 'damaged vehicle'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '336',
    title: 'Forgery',
    description: 'Whoever makes any false document or part of a document with intent to cause damage or injury to the public or to any person.',
    plain_language: 'Creating or using fake/forged documents.',
    offense_category: 'Forgery & Fraud',
    punishment: 'Imprisonment up to 2 years, or fine, or both; forging court documents — up to 7 years',
    is_bailable: false,
    is_cognizable: false,
    typical_evidence: ['Original and forged documents', 'Handwriting expert report', 'Digital forensics', 'Witness statements'],
    keywords: ['forgery', 'forged document', 'fake document', 'fabricated', 'counterfeit', 'false document'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '351',
    title: 'Criminal Intimidation',
    description: 'Whoever threatens another with any injury to his person, reputation or property with intent to cause alarm to that person.',
    plain_language: 'Threatening someone to cause fear or compel them to do something.',
    offense_category: 'Intimidation',
    punishment: 'Imprisonment up to 2 years, or fine, or both; threat of death or grievous hurt — up to 7 years',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Threat messages/calls', 'Victim statement', 'Call records', 'Witness statements'],
    keywords: ['threat', 'intimidation', 'threatening', 'extortion threat', 'death threat', 'warning'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '85',
    title: 'Husband or Relatives of Husband Subjecting Woman to Cruelty',
    description: 'Whoever being the husband or the relative of the husband of a woman, subjects such woman to cruelty.',
    plain_language: 'Domestic violence or dowry-related harassment of a married woman by husband or in-laws.',
    offense_category: 'Domestic Violence',
    punishment: 'Imprisonment up to 3 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Victim statement', 'Medical report', 'Witness statements', 'Call records', 'Photographs of injuries'],
    keywords: ['domestic violence', 'cruelty', 'dowry harassment', 'wife beaten', 'marital cruelty', '498A', 'husband cruelty'],
  },
  {
    act_name: 'Bharatiya Nyaya Sanhita, 2023',
    section: '80',
    title: 'Dowry Death',
    description: 'Where the death of a woman is caused by burns or bodily injury or occurs under suspicious circumstances within 7 years of marriage, and it is shown that she was subjected to cruelty or harassment by husband or in-laws for dowry.',
    plain_language: 'Death of a bride due to dowry demands or harassment by husband or in-laws.',
    offense_category: 'Dowry Death',
    punishment: 'Imprisonment not less than 7 years, may extend to life imprisonment',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Post-mortem report', 'Witness statements', 'Family history', 'Call records', 'Dowry demand evidence'],
    keywords: ['dowry death', 'bride burning', 'dowry killing', 'unnatural death', 'suspicious death bride', '304B'],
  },
  // ─── IT Act 2000 ──────────────────────────────────────────────────────────
  {
    act_name: 'Information Technology Act, 2000',
    section: '43',
    title: 'Penalty for Damage to Computer Systems',
    description: 'Whoever without permission of the owner accesses or secures access to a computer, computer system, or network shall be liable to pay damages by way of compensation.',
    plain_language: 'Unauthorized access to someone\'s computer, network, or data.',
    offense_category: 'Cybercrime',
    punishment: 'Compensation up to Rs. 1 Crore',
    is_bailable: true,
    is_cognizable: false,
    typical_evidence: ['Server logs', 'Digital forensic report', 'IP address records', 'Network logs'],
    keywords: ['hacking', 'unauthorized access', 'computer access', 'network breach', 'data theft', 'cyber intrusion'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '66',
    title: 'Computer Related Offences',
    description: 'If any person, dishonestly or fraudulently does any act referred to in section 43, he shall be punishable with imprisonment up to 3 years or fine up to five lakh rupees.',
    plain_language: 'Fraudulent or dishonest computer crimes including hacking, data theft, and virus spreading.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 3 years, or fine up to Rs. 5 lakhs, or both',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Digital forensic report', 'Server logs', 'IP records', 'Device seized'],
    keywords: ['hacking', 'cybercrime', 'computer fraud', 'data breach', 'virus', 'malware', 'cyber attack'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '66C',
    title: 'Identity Theft',
    description: 'Whoever fraudulently or dishonestly makes use of the electronic signature, password or any other unique identification feature of any other person.',
    plain_language: 'Stealing and using someone\'s digital identity, passwords, or electronic signatures.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 3 years and fine up to Rs. 1 lakh',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Account records', 'Login logs', 'Device forensics', 'Bank records'],
    keywords: ['identity theft', 'password theft', 'OTP fraud', 'account hacking', 'digital identity theft'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '66D',
    title: 'Cheating by Personation Using Computer Resources',
    description: 'Whoever by means of any communication device or computer resource cheats by personation.',
    plain_language: 'Online fraud by pretending to be someone else using computers or phones.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 3 years and fine up to Rs. 1 lakh',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Fake profile/account records', 'Digital evidence', 'Call/chat records', 'Bank records'],
    keywords: ['online fraud', 'cyber fraud', 'fake account', 'phishing', 'impersonation online', 'KYC fraud'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '66E',
    title: 'Violation of Privacy',
    description: 'Whoever intentionally or knowingly captures, publishes or transmits the image of a private area of any person without his or her consent.',
    plain_language: 'Secretly capturing or sharing intimate images or videos of a person without consent.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 3 years, or fine up to Rs. 2 lakhs, or both',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Digital evidence', 'Victim statement', 'Device forensics', 'Social media records'],
    keywords: ['privacy violation', 'MMS', 'intimate video leaked', 'private photo shared', 'revenge porn', 'upskirt video'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '67',
    title: 'Publishing Obscene Material in Electronic Form',
    description: 'Whoever publishes or transmits or causes to be published in the electronic form, any material which is lascivious or appeals to the prurient interest.',
    plain_language: 'Sharing or publishing pornographic or obscene content online.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 3 years and fine up to Rs. 5 lakhs for first conviction',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Device forensics', 'Social media records', 'URL/IP records', 'Digital evidence'],
    keywords: ['obscene content', 'pornography', 'obscene video', 'adult content sharing', 'indecent material online'],
  },
  {
    act_name: 'Information Technology Act, 2000',
    section: '67B',
    title: 'Child Pornography',
    description: 'Whoever publishes or transmits material in any electronic form which depicts children in obscene or indecent or sexually explicit manner.',
    plain_language: 'Creating, sharing, or possessing child sexual abuse material (CSAM) online.',
    offense_category: 'Cybercrime',
    punishment: 'Imprisonment up to 5 years and fine up to Rs. 10 lakhs for first conviction; 7 years for subsequent',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Device forensics', 'Internet records', 'Digital evidence', 'Email/chat records'],
    keywords: ['child pornography', 'CSAM', 'child sexual abuse material', 'minor pornography', 'child exploitation online'],
  },
  // ─── NDPS Act 1985 ────────────────────────────────────────────────────────
  {
    act_name: 'Narcotic Drugs and Psychotropic Substances Act, 1985',
    section: '20',
    title: 'Punishment for Contravention of Cannabis',
    description: 'Whoever in contravention of any provision of the Act produces, manufactures, possesses, sells, purchases, transports, imports or exports cannabis.',
    plain_language: 'Illegal production, possession, sale, or transport of cannabis/marijuana/ganja.',
    offense_category: 'Drug Offence',
    punishment: 'Small quantity: up to 1 year; commercial quantity: rigorous imprisonment 10-20 years and fine Rs.1-2 lakhs',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Seized substance', 'FSL chemical analysis report', 'Panchnama', 'Witness statements', 'Search warrant'],
    keywords: ['ganja', 'cannabis', 'marijuana', 'drugs seized', 'drug trafficking', 'weed', 'bhang'],
  },
  {
    act_name: 'Narcotic Drugs and Psychotropic Substances Act, 1985',
    section: '21',
    title: 'Punishment for Contravention of Manufactured Drugs',
    description: 'Whoever in contravention of any provision contravenes any provision relating to manufactured drugs and preparations.',
    plain_language: 'Illegal possession, sale or trafficking of heroin, morphine, cocaine, or other manufactured drugs.',
    offense_category: 'Drug Offence',
    punishment: 'Small quantity: up to 1 year; commercial quantity: 10-20 years rigorous imprisonment and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Seized drugs', 'FSL report', 'Panchnama', 'Witness statements', 'Financial records'],
    keywords: ['heroin', 'cocaine', 'morphine', 'smack', 'brown sugar', 'drug trafficking', 'narcotics'],
  },
  {
    act_name: 'Narcotic Drugs and Psychotropic Substances Act, 1985',
    section: '27A',
    title: 'Financing Illicit Drug Traffic',
    description: 'Whoever indulges in financing directly or indirectly, any person, group or organisation for illicit traffic.',
    plain_language: 'Funding or financing drug trafficking operations.',
    offense_category: 'Drug Offence',
    punishment: 'Rigorous imprisonment 10-20 years and fine Rs. 1-2 lakhs',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Financial records', 'Bank statements', 'Call records', 'Witness statements', 'Digital evidence'],
    keywords: ['drug financing', 'funding drug trade', 'drug cartel', 'drug money', 'narco finance'],
  },
  // ─── POCSO Act 2012 ───────────────────────────────────────────────────────
  {
    act_name: 'Protection of Children from Sexual Offences Act, 2012',
    section: '4',
    title: 'Penetrative Sexual Assault on Child',
    description: 'Whoever commits penetrative sexual assault on a child shall be punished.',
    plain_language: 'Sexual penetration of a child (below 18 years) — the most serious child sexual offence.',
    offense_category: 'Child Sexual Offence',
    punishment: 'Rigorous imprisonment not less than 20 years, may extend to life imprisonment or death',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical examination', 'Child statement (recorded by magistrate)', 'Forensic DNA', 'Witness statements'],
    keywords: ['child rape', 'POCSO', 'child sexual assault', 'minor raped', 'child abuse', 'penetrative assault child'],
  },
  {
    act_name: 'Protection of Children from Sexual Offences Act, 2012',
    section: '7',
    title: 'Sexual Assault on Child',
    description: 'Whoever with sexual intent touches the vagina, penis, anus or breast of the child or makes the child touch the vagina, penis, anus or breast of such person or any other person.',
    plain_language: 'Sexual touching or molestation of a child without penetration.',
    offense_category: 'Child Sexual Offence',
    punishment: 'Imprisonment not less than 3 years, may extend to 5 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Medical examination', 'Child statement', 'Witness statements', 'CCTV'],
    keywords: ['child molestation', 'POCSO', 'child touched', 'minor molested', 'sexual assault child', 'indecent touching'],
  },
  {
    act_name: 'Protection of Children from Sexual Offences Act, 2012',
    section: '11',
    title: 'Sexual Harassment of Child',
    description: 'A person is said to commit sexual harassment upon a child when such person utters any word or makes any sound, or makes any gesture, or exhibits any object or part of body with sexual intent.',
    plain_language: 'Sexual gestures, words, or exhibitionism directed at a child.',
    offense_category: 'Child Sexual Offence',
    punishment: 'Imprisonment up to 3 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Child statement', 'Witness statements', 'Call/chat records', 'Social media evidence'],
    keywords: ['child sexual harassment', 'POCSO harassment', 'minor harassed', 'inappropriate gesture child'],
  },
  // ─── Motor Vehicles Act 1988 ──────────────────────────────────────────────
  {
    act_name: 'Motor Vehicles Act, 1988',
    section: '184',
    title: 'Driving Dangerously',
    description: 'Whoever drives a motor vehicle at a speed or in a manner which is dangerous to the public, having regard to all the circumstances.',
    plain_language: 'Driving in a dangerous or reckless manner that endangers public safety.',
    offense_category: 'Traffic Offence',
    punishment: 'First offence: imprisonment up to 6 months or fine Rs. 1,000-5,000; subsequent: up to 2 years or fine',
    is_bailable: true,
    is_cognizable: true,
    typical_evidence: ['FIR', 'Witness statements', 'CCTV', 'Accident report', 'Speed camera records'],
    keywords: ['rash driving', 'dangerous driving', 'over-speeding', 'reckless driving', 'road accident'],
  },
  {
    act_name: 'Motor Vehicles Act, 1988',
    section: '185',
    title: 'Driving by a Drunken Person',
    description: 'Whoever drives or attempts to drive a motor vehicle in any public place while under the influence of alcohol or drugs.',
    plain_language: 'Driving while drunk or under influence of drugs.',
    offense_category: 'Traffic Offence',
    punishment: 'First offence: up to 6 months imprisonment or Rs. 10,000 fine; second offence: up to 2 years or Rs. 15,000',
    is_bailable: true,
    is_cognizable: true,
    typical_evidence: ['Breathalyser test report', 'Blood alcohol report', 'Witness statements', 'CCTV'],
    keywords: ['drunk driving', 'DUI', 'driving under influence', 'drunk and drive', 'alcohol driving'],
  },
  // ─── Arms Act 1959 ────────────────────────────────────────────────────────
  {
    act_name: 'Arms Act, 1959',
    section: '25',
    title: 'Punishment for Certain Offences',
    description: 'Whoever acquires, has in his possession or carries any firearm or ammunition in contravention of section 3.',
    plain_language: 'Illegal possession of firearms or ammunition without a valid licence.',
    offense_category: 'Arms Offence',
    punishment: 'Imprisonment up to 3 years, or fine, or both; if used in crime — up to 7 years',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Seized firearm/ammunition', 'Ballistics report', 'Panchnama', 'Witness statements'],
    keywords: ['illegal arms', 'illegal weapon', 'unlicensed firearm', 'country made pistol', 'arms possession', 'gun seized'],
  },
  // ─── Prevention of Corruption Act 1988 ───────────────────────────────────
  {
    act_name: 'Prevention of Corruption Act, 1988',
    section: '7',
    title: 'Offence Relating to Public Servant Being Bribed',
    description: 'Whoever being or expecting to be a public servant accepts or obtains or agrees to accept or attempts to obtain from any person any gratification whatsoever other than legal remuneration.',
    plain_language: 'A government/public official accepting bribe or illegal gratification.',
    offense_category: 'Corruption',
    punishment: 'Imprisonment not less than 3 years, may extend to 7 years and fine',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Trap case panchnama', 'Marked currency', 'Anti-Corruption Bureau report', 'Witness statements', 'Audio/video recording'],
    keywords: ['bribery', 'corruption', 'bribe', 'gratification', 'public servant bribe', 'illegal money', 'trap case', 'ACB case'],
  },
  // ─── SC/ST Act 1989 ───────────────────────────────────────────────────────
  {
    act_name: 'Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989',
    section: '3',
    title: 'Offences of Atrocities',
    description: 'Whoever, not being a member of SC/ST, commits any offence of atrocities including assault, humiliation, economic exploitation, or denial of rights on the basis of caste.',
    plain_language: 'Caste-based discrimination, violence, or humiliation against SC/ST community members.',
    offense_category: 'Atrocity',
    punishment: 'Imprisonment not less than 6 months, may extend to 5 years and fine; serious offences — life imprisonment',
    is_bailable: false,
    is_cognizable: true,
    typical_evidence: ['Victim statement', 'Caste certificate', 'Witness statements', 'Medical report', 'Video evidence'],
    keywords: ['SC/ST atrocity', 'caste discrimination', 'dalit atrocity', 'untouchability', 'caste violence', 'casteism'],
  },
];

const seed = async () => {
  const uri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/justice_ai';
  await mongoose.connect(uri);
  console.log('Connected to MongoDB');

  // Remove old provisions and re-seed fresh
  await LegalProvision.deleteMany({});
  console.log('Cleared existing provisions');

  const result = await LegalProvision.insertMany(PROVISIONS);
  console.log(`✅ Seeded ${result.length} real Indian legal provisions`);

  // Log summary by act
  const summary = PROVISIONS.reduce((acc, p) => {
    acc[p.act_name] = (acc[p.act_name] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log('\nProvisions by Act:');
  Object.entries(summary).forEach(([act, count]) => {
    console.log(`  ${act}: ${count} sections`);
  });

  await mongoose.disconnect();
  console.log('\nDone.');
};

seed().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
